---
permalink: linux-administration/concept_supported_partition_devices.html
sidebar: sidebar
keywords: snap, snapdrive, support, storage, partitioning, multipathing
summary: SnapDrive for UNIX 5.0 or later provides storage partitioning in Linux for multipathing and non-multipathing environment.
---
= Supported partition devices
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX 5.0 or later provides storage partitioning in Linux for multipathing and non-multipathing environment.

You must follow the guidelines to partition storage devices with SnapDrive for UNIX.

When you are using Logical Volume Manager with Linux, you must use non-partitioned LUNs.

The following tables provide partition information and how it can be enabled for different operating systems:

[options="header"]
|===
| Operating system| Single partition| Multiple partition| Non-partition devices| File system or RAW devices
a|
Red Hat Enterprise Linux 5x

or

Oracle Enterprise Linux 5x
a|
Yes
a|
No
a|
No
a|
ext3*
a|
Red Hat Enterprise Linux 6x

or

Oracle Enterprise Linux 6x
a|
Yes
a|
No
a|
No
a|
ext3 or ext4*
a|
SUSE Linux Enterprise Server 11
a|
Yes
a|
No
a|
No
a|
ext3*
a|
SUSE Linux Enterprise Server 10
a|
No
a|
No
a|
Yes
a|
ext3***
a|
Red Hat Enterprise Linux 5x or later

or

Oracle Enterprise Linux 5x or later
a|
Yes
a|
No
a|
Yes
a|
ASM with ASMlib**
a|
SUSE Linux Enterprise Server 10 SP4

or

SUSE Linux Enterprise Server 11
a|
Yes
a|
No
a|
Yes
a|
ASM with ASMlib**
a|
SUSE Linux Enterprise Server 10 SP4 or later

or

SUSE Linux Enterprise Server 11
a|
Yes
a|
No
a|
No
a|
ASM without ASMlib****
5+a|
*

For a non-MPIO environment, enter the following command: `*sfdisk -uS -f -L -q /dev/ _device_name_*`

For an MPIO environment, enter the following commands:

* `*sfdisk -uS -f -L -q /dev/ _device_name_*`
* `*kpartx -a -p p /dev/mapper/ _device_name_*`
5+a|
**

For a non-MPIO environment, enter the following command:
`*fdisk /dev/_device_name_*`

For an MPIO environment, enter the following commands:

* `*fdisk /dev/mapper/_device_name_*`
* `*kpartx -a -p p /dev/mapper/_device_name_*`
5+a|
\***

Not applicable.

5+a|
\****

For an MPIO environment, enter the following command:

* `*kpartx -a -p p /dev/$kernel*`

|===
*General considerations*

The Snapshot copies created in SnapDrive for UNIX 4.2 are based on partitioned devices. These Snapshot copies can be restored, connected, and supported in SnapDrive for UNIX 5.0 and later versions.
