---
permalink: linux-administration/concept_guidelines_for_thesnapdrive_storagedisconnectcommand.html
sidebar: sidebar
keywords: 
summary: 'Follow these guidelines when using the snapdrive storage disconnect command:'
---
= Guidelines for the snapdrive storage disconnect command
:icons: font
:imagesdir: ../media/

[.lead]
Follow these guidelines when using the snapdrive storage disconnect command:

* When you disconnect a file system, SnapDrive for UNIX always removes the mountpoint.
+
Linux hosts allow you to attach multiple file systems to a single mountpoint. However, SnapDrive for UNIX requires a unique mountpoint for each file system. The snapdrive storage disconnectcommand fails if you use it to disconnect file systems that are attached to a single mountpoint.

* If you use the -lun option to specify the name of a LUN that is a member of either a host disk group, or a file system, the snapdrive storage disconnect command fails.
* If you use -lun option to specify the name of the LUN that is not discovered by multipathing software on the host, the snapdrive storage disconnect command fails.

NOTE: snapdrive storage disconnect command fails while using RDM LUN, if the mapping igroup has more than two World Wide Port Names (WWPN), in releases prior to SnapDrive 5.2 for UNIX.
