---
permalink: linux-administration/concept_informationrequired_forusing_the_snapdrive_snapshow_or_list_commands.html
sidebar: sidebar
keywords: snap, snapdrive, list, command, storage, display, show
summary: 'You can use the command snapdrive snap show or list to display information about storage systems, storage system volumes, disks, or volume groups, file system, Snapshot copies, and so on.'
---
= Information required for using the snapdrive snap show or list commands
:icons: font
:imagesdir: ../media/

[.lead]
You can use the command snapdrive snap show or list to display information about storage systems, storage system volumes, disks, or volume groups, file system, Snapshot copies, and so on.

The following table gives the information you need to supply when you use the snapdrive snap show | list command.

NOTE: You can use the same arguments regardless of whether you enter snapdrive snap show or snapdrive snap list as the command. These commands are synonyms.

|===
| Requirement/Option| Argument
a|
Based on the command you enter, you can display information about any of the following:

* Storage systems
* Storage system volumes
* Disk or volume groups
* File systems
* Host or logical volumes
* Snapshot copies

The value you enter for the file_spec argument must identify the storage entity about which you want to display information. The command assumes the entities are on the current host.

a|
Storage system (-filer)
a|
filername
a|
A volume on the storage system (-filervol)
a|
filervol
a|
Disk group (-dgfile_spec) or volume group (-vgfile_spec)

a|
name of the disk or volume group
a|
File system (-fsfile_spec)
a|
filesystem_name
a|
Host volume (-hostvolfile_spec) or logical volume (-lvolfile_spec)

a|
name of the host or logical volume
a|
Snapshot copy name (-snapnamelong_snap_name)
a|
long_snap_name
a|
Additional Snapshot copy names
a|
snap_name (long or short version)
a|
If you want to display information about a Snapshot copy, specify the name for the Snapshot copy. For the first Snapshot copy, long_snap_name, enter the long version of the name, which includes the storage system name, volume, and Snapshot copy name. You can use the short version of the Snapshot copy name if it is on the same storage system and volume.

a|
-verbose
a|
~
a|
To display additional information, include the -verbose option.
|===
