---
permalink: linux-administration/concept_snapdrive_for_unix_reports_an_error_if_iscsi_is_not_running.html
sidebar: sidebar
keywords: snap, snapdrive, unix, error, iscsi, takeover, giveback
summary: SnapDrive for UNIX running on a Linux host returns an error message as “HBA assistant not found”.
---
= SnapDrive for UNIX reports an error if iSCSI is not running
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX running on a Linux host returns an error message as "`HBA assistant not found`".

This happens after one of the following situations occurs:

* An iSCSI stop was issued.
* A takeover has happened and the iSCSI service has not started yet.
* A giveback is happening and the iSCSI service has not started yet.

For SnapDrive for UNIX to execute, the iSCSI service must be running. If the service is halted, SnapDrive for UNIX returns an error message. For example, if you execute the snapdrive storage show command when the iSCSI service is not running, you might view the output similar to the following: `# snapdrive storage show -dg toaster1 0001-877 Admin error: HBA assistant not found. Commands involving LUNs should fail.`

== Workaround

Ensure the iSCSI service is running. If the storage system is in the process of a takeover or giveback, wait until it starts the iSCSI service. If the storage system is in normal running mode, restart the iSCSI service and then restart the SnapDrive for UNIX daemon by running the `snapdrived restart` command. After the service is running, reissue the `snapdrive storage show` command. This time you should see output similar to the following:

----
# snapdrive storage show -dg toaster1
dg: toaster1 dgtype lvm
hostvol: /dev/mapper/toaster1-lvol1 state: AVAIL
hostvol: /dev/mapper/toaster1-lvol2 state: AVAIL
fs: /dev/mapper/toaster1-lvol1 mount point: /mnt/um1 (nonpersistent)
fstype ext3
fs: /dev/mapper/toaster1-lvol2 mount point: NOT MOUNTED
device filename adapter path size proto state clone lun path backing snapshot
/dev/sde - P 64m iscsi online No gin:/vol/vol1/Lun1
/dev/sdf - P 64m iscsi online No gin:/vol/vol1/Lun2
----
