---
permalink: linux-administration/concept_what_flexclone_volumes_are.html
sidebar: sidebar
keywords: snap, snapdrive, flexcone, volume, parent, clone
summary: 'A flexible volume clone, FlexClone, is a point-in-time copy of a parent flexible volume. The FlexClone volume does not inherit the changes made to the parent flexible volume after the clone is created.'
---
= What FlexClone volumes are
:icons: font
:imagesdir: ../media/

[.lead]
A flexible volume clone, FlexClone, is a point-in-time copy of a parent flexible volume. The FlexClone volume does not inherit the changes made to the parent flexible volume after the clone is created.

Data ONTAP FlexClone technology enables instant replication of data volumes without requiring additional storage space at the time of creation. Each clone volume is a transparent, virtual copy that you can use for a wide range of operations such as product or system development testing, bug fixing, upgrade checks, and so on.

FlexClone technology provides substantial space savings with minimal overhead. Using this technology you can manage many more dataset combinations in lesser time and with less risk. FlexClone volumes do not have write reservation by default. SnapDrive 4.1 for UNIX uses FlexClone technology in NFS and SAN environments.

NOTE: FlexClone volumes are supported on Data ONTAP 7.0.x and later, but they are not supported with vFiler units on storage systems running Data ONTAP 7.2 or earlier.
