---
permalink: linux-administration/concept_snapdrive_for_unix_command_displays_could_not_check_access_error.html
sidebar: sidebar
keywords: snap, snapdrive, command, display, access, error, object
summary: SnapDrive for UNIX may display error when it does have proper write access on the storage object.
---
= SnapDrive for UNIX command displays could not check access error
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX may display error when it does have proper write access on the storage object.

It displays the following error message:

----
0002-332 Admin error: Could not check SD.Storage.Write access on LUN storage_array1:/vol/vol1/lun1for user unix-host\root
 on Operations Manager server(s) ops-mngr-server1 reason: Invalid resource specified.  Unable to find its Id on Operations Manager server ops-mngr-server1
----

The solution for this problem is to:

. Verify that the storage resource is refreshed on Operations Manager. If storage resource is not refreshed on Operations Manager, then
 ** Manually execute `dfm host discover <storage-system>`.
 ** Assign {Global, DFM.Database.Write} capability to `sd-admin`
+
In this case, SnapDrive for UNIX automatically refresh Operations Manager and reissue access check.

The default refresh interval used by SnapDrive for UNIX is 15 seconds (`_dfm-rbac-retry-sleep-secs_`) and the default number of retries used by SnapDrive for UNIX is 12 (`_dfm-rbac-retries_`). If you still receive the above error message, then increase the value of `_dfm-rbac-retries_` configuration variable to 14, 16, 18... and so on to match your environment. The refresh interval required by Operations Manager depends on the number of LUNs and volumes you have in your storage system.
