---
permalink: linux-administration/concept_types_of_logs.html
sidebar: sidebar
keywords: 
summary: 'SnapDrive for UNIX supports various types of log files, which help you troubleshoot when SnapDrive for UNIX is not working as expected.'
---
= Types of logs
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX supports various types of log files, which help you troubleshoot when SnapDrive for UNIX is not working as expected.

* Audit log
+
SnapDrive for UNIX logs all commands and their return codes in an audit log. SnapDrive for UNIX makes an entry when you initiate a command and another when the command is complete. The later entry includes both the status of the command and the completion time.

* Recovery log
+
Some SnapDrive for UNIX operations have the potential to leave the system in an inconsistent or less usable state if interrupted. This situation could occur if a user terminates the program, or if the host crashes in the middle of an operation. The recovery log contains the steps of a Snap restore operation. It documents the steps that are taken and the progress made so that technical support can assist you with the manual recovery process.

* Trace log
+
SnapDrive for UNIX reports information useful for diagnosing problems. If you have a problem, NetApp technical support might request this log file.
+
SnapDrive 4.0 for UNIX introduced SnapDrive for UNIX daemon service. For SnapDrive for UNIX commands to run, the daemon must be running. Daemon tracing must be carried out on for each individual command, even when commands are run in parallel. The location and name of the log file is /var/log/sd-trace.log. These trace files have only the command-specific trace entries. The trace logs for daemon execution are recorded in a different trace file /var/log/sd-daemon-trace.log.
