---
permalink: linux-administration/concept_0001_680_admin_error_host_os_requires_an_update_to_internal_data_after_each_reboot.html
sidebar: sidebar
keywords: snap, snapdrive, reboot, error, update, connect, admin
summary: 'On Red Hat Enterprise Linux 4 and Oracle Enterprise Linux 4 hosts, after every reboot the Snapshot connect and storage create operations encounters an error message.'
---
= After each reboot snap connect yields "0001-680 Admin error: Host OS requires an update to internal data"
:icons: font
:imagesdir: ../media/

[.lead]
On Red Hat Enterprise Linux 4 and Oracle Enterprise Linux 4 hosts, after every reboot the Snapshot connect and storage create operations encounters an error message.

The following error message occurs because the sg driver deletes all the inactive device in /dev/sgXX file after a reboot.

== Workaround

. Check the value of the configuration variable enable-implicithost- preparation in the /opt/Netapp/snapdrive/snapdrive.conf file. It should be set to on.
+
After rebooting the host and before using SnapDrive for UNIX, complete the following steps.

. Verify that the sg and iSCSI services are loaded by entering the following command:
+
lsmod

. If the sg and iSCSI (if iSCSI setup is used) services are not loaded, enter the following commands:
 ** modprobe sg
 ** service iscsi start
*Note:* If you do not want to perform steps 2 and 3 manually, add the modprobe sg and service iscsi start commands in the host startup script.
