---
permalink: linux-administration/concept_what_snapshot_operations_are_in_snapdrive_for_unix.html
sidebar: sidebar
keywords: snap, snapdrive, snapshot, ontap, image, host, storage, data, unix
summary: SnapDrive for UNIX enables you to use Data ONTAP Snapshot technology to make an image \(Snapshot copy\) of host data that is stored on a storage system.
---
= What Snapshot operations are in SnapDrive for UNIX
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX enables you to use Data ONTAP Snapshot technology to make an image (Snapshot copy) of host data that is stored on a storage system.

This Snapshot copy provides you with a copy of that data, which you can restore later. The data in the Snapshot copy can exist on one storage system or span multiple storage systems and their volumes. These storage systems can be in HA pair or node-local file systems or disk groups or LUNs in a host cluster environment. On a nonclustered UNIX host with SnapDrive for UNIX installed, you can create a Snapshot copy of one or more volume groups on a storage system.

The Snapshot copy can contain file systems, logical volumes, disk groups, LUNs, and NFS directory trees. After you create a Snapshot copy, you can rename, restore, or delete it. You can also connect to a different location on the same host or to a different host. After you connect, you can view and modify the content of the Snapshot copy, or you can disconnect the Snapshot copy. In addition, SnapDrive for UNIX enables you to display information about the Snapshot copy that you have created. On a clustered UNIX host with SnapDrive for UNIX installed, you can perform Snapshot operations on the host cluster nodes that includes disk groups and file systems. The Snapshot operations include create, rename, restore, connect, disconnect, display, and delete.
