---
permalink: linux-administration/concept_guidelines_fordisconnectingsnapshot_copies.html
sidebar: sidebar
keywords: snap, snapdrive, disconnect, snapshot, copy, lun, storage, nfs
summary: The following are the guidelines to disconnect a Snapshot copy for LUNs, storage entities, or NFS directories.
---
= Guidelines for disconnecting Snapshot copies
:icons: font
:imagesdir: ../media/

[.lead]
The following are the guidelines to disconnect a Snapshot copy for LUNs, storage entities, or NFS directories.

* When you disconnect a file system, SnapDrive for UNIX always removes the mountpoint.
* Linux hosts allow you to attach multiple file systems to a single mountpoint. However, SnapDrive for UNIX requires a unique mountpoint for each file system. The `snapdrive snap disconnect` command fails if you use it to disconnect file systems that are attached to a single mountpoint.
* To undo the effects of the Snapshot connect operation, use the Snapshot disconnect command.
* If you set the `enable-split-clone` configuration variable value to `on` or `sync` during the Snapshot connect operation and `off` during the Snapshot disconnect operation, SnapDrive for UNIX does not delete the original volume or LUN that is present in the Snapshot copy.
