---
permalink: linux-administration/concept_using_selective_lun_map_in_snapdrive_for_unix.html
sidebar: sidebar
keywords: snap, snapdrive, lun, selective, map, path, ha, data, clustered, slm
summary: Beginning with clustered Data ONTAP 8.3, Selective LUN Map \(SLM\) is enabled by default on all new LUN maps. When you create a new LUN map, the LUN is accessible only through paths found on the node that owns that LUN and its HA partner.
---
= Using Selective LUN Map in SnapDrive for UNIX
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with clustered Data ONTAP 8.3, Selective LUN Map (SLM) is enabled by default on all new LUN maps. When you create a new LUN map, the LUN is accessible only through paths found on the node that owns that LUN and its HA partner.

By default, LUNs are accessible on all the LIFs of a Storage Virtual Machine (SVM). You should assign LIFs to the SVMs on each cluster node in your network. As the number of nodes in the cluster increases, the number of potential paths also multiplies. This can result in an excessive number of paths to a LUN, multiple igroups per host, and disruptive mobility events. SLM solves these problems by restricting LUN accessibility to the node that owns the LUN and the HA partner node. It also creates a single igroup per host and supports non-disruptive LUN mobility operations that do not require portset manipulation or LUN remapping.

NOTE: SLM does not automatically apply to LUN maps created prior to clustered Data ONTAP 8.3.

If you are accessing the LUN through the node that owns the LUN, the path is called "active optimized." However, if you access that LUN through the HA partner node, the path is called "active non-optimized."

[options="header"]
|===
| SnapDrive command| Description
a|
`snapdrive lun showpaths _long_lun_name_`
a|
The `snapdrive lun showpaths` command lists all the paths to LUN. It also displays which path is active optimized and which path is active non-optimized.

`_long_lun_name_` is the name of the LUN. If you do not specify the LUN, the operation is performed on all the LUNs.

----
snapdrive lun showpaths
lun path            device filename                   asymmetric access state
------------------------------------------------------------------------------
vs1:/vol/vol2/lun10  /dev/mapper/3600a09807746505a4e24455450473655   Non-optimized
vs1:/vol/vol2/lun2  /dev/mapper/3600a09807746505a4d3f455432474b30    Optimized
vs1:/vol/vol2/lun1  /dev/mapper/3600a09807746505a4e24455450473656    Optimized
----

a|
`snapdrive lun fixpaths _long_lun_name_`
a|
The `snapdrive lun fixpaths` command tries to fix the path of the LUNs for the LUNs that do not have at least one active optimized path.

`_long_lun_name_` is the name of the LUN. If you do not specify the LUN, the operation is performed on all the LUNs that do not have at least one active optimized path.

----
snapdrive lun fixpaths
The following LUNs are using Non-optimized paths
-------------------------------------------------
vs1:/vol/vol2/lun10

Path correction successful for the following LUNs
--------------------------------------------------
vs1:/vol/vol2/lun10
----

NOTE: The `snapdrive lun fixpaths` command does not work in guest operating system.

|===
The `lunpath-monitor-frequency` parameter allows you to specify the frequency in which SnapDrive for UNIX automatically fix path for LUNs. The default value is 24 hours.

If the `snapdrive lun fixpaths` operation fails, an AutoSupport (ASUP) message is generated for all the LUNs. The ASUP message contains the following details:

* computerName
* eventSource
* appVersion
* eventID
* category
* subject

The following is an example of an ASUP message:

----
computerName="owhyee"
       eventSource="snapdrive"
       appVersion="5.2.2 for UNIX"
       eventID="6"
       category="lun path"
       subject="Paths are misconfigured for the Luns /vol/June12v1/LUN2 in storage system sdu_100_101_60_62_vs1 on owhyee host."
----

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[ONTAP 9 SAN Administration Guide]
