---
permalink: linux-administration/concept_command_syntax_to_increase_the_sizeof_the_storage.html
sidebar: sidebar
keywords: snap, snapdrive, command, syntax, size, storage, increase
summary: 'To increase the size of the storage, you should know the correct syntax to be used.'
---
= Command syntax to increase the size of the storage
:icons: font
:imagesdir: ../media/

[.lead]
To increase the size of the storage, you should know the correct syntax to be used.

`snapdrive storage resize -dg _file_spec_ { -growby | -growto } size [-addlun [-igroup _ig_name_ [_ig_name ..._]]] [{ -reserve | - noreserve}]] [-fstype _type_] [-vmtype _type_]`

[NOTE]
====
You cannot use the `snapdrive storage resize` command to reduce the size of an entity. You can only increase the size using this command.

The `snapdrive storage resize` command does not support directly on logical volumes or file systems. For example, you cannot use the `snapdrive storage resize` command to resize a file system on a LUN.

*Result*: This command increases the size of the storage entity (logical volume or disk group) by either of the following:

* Adding bytes to storage (`-growby`).
* Increasing the size to the byte size you specify (`-growto`).
====
