---
permalink: linux-administration/concept_example_of_an_autosupport_message.html
sidebar: sidebar
keywords: 
summary: 'SnapDrive for UNIX provides examples for different scenarios. The content of an AutoSupport message in all the examples are essentially the same regardless of your operating system.'
---
= Examples of AutoSupport messages
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX provides examples for different scenarios. The content of an AutoSupport message in all the examples are essentially the same regardless of your operating system.

Example: Adding a new storage system

The following example is a message sent from a host named x336-207-58:

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="sduvs2 configured"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp
----

Example: Restarting the Daemon

SnapDrive for UNIX sends the following AutoSupport message to the storage system, when you restart the daemon:

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp
----

SnapDrive for UNIX sends the following AutoSupport message to the storage system, if dfm is configured and rbac-method is set to dfm:

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=dfm, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=Yes, Protocol=fcp"
----

SnapDrive for UNIX sends the following AutoSupport message to the storage system, if dfm is configured and rbac-method is set to native.

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=Yes, Protocol=fcp"
----

SnapDrive for UNIX sends the following AutoSupport message to the storage system when a snap create operation succeeds:

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=3, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=iscsi, snapshot_name=dg_snap"
----

SnapDrive for UNIX sends the following AutoSupport message to the storage system when the storage show all operation succeeds:

----
computerName="x336-207-58"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="general"
        subject="protos=fcp, Connect Luns=8, dgs=4, hvs=3, fs=3, host_name=x336-207-58, host_os=Linux, host_os_release=2.6.32-279.el6.x86_64, host_os_version=#1 SMP Wed Jun 13 18:24:36 EDT 2012, No of controller=2, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
