---
permalink: linux-administration/concept_migrating_to_new_vserver_name.html
sidebar: sidebar
keywords: snap, snapdrive, vserver, name, migrate, host, operations
summary: 'If you have migrated from an old Vserver to a new Vserver, you must ensure that the new Vserver name is configured on the host system to execute any SnapDrive operations on the Vserver.'
---
= Migrating to new Vserver name
:icons: font
:imagesdir: ../media/

[.lead]
If you have migrated from an old Vserver to a new Vserver, you must ensure that the new Vserver name is configured on the host system to execute any SnapDrive operations on the Vserver.

The following steps must be performed on the host system whenever you migrate to a new Vserver name:

.Steps

. Delete the old Vserver name that is configured using the following command:
+
`*snapdrive config delete _appliance_name_*`
+
The old configured Vserver name is removed from the host system.

. Delete the port set that is assigned to the old configured Vserver using the following command:
+
`*snapdrive portset delete _filername_ [_filername..._]*`
. Configure the new Vserver name using the following command:
+
`*snapdrive config set _vsadmin filername_ [_filername..._]*`
. Assign the port set using the following command:
+
`*snapdrive portset add _portset_name_ filername [_filername..._]*`
. Migrate the new Vserver name using the following command:
`*snapdrive config migrate set _old_entrynew_entry_*`

After you have migrated to the new Vserver, you are ready to execute SnapDrive operations in the host system for this new Vserver name.

*Related information*

xref:task_migrating_from_old_host_name_to_new_host_name.adoc[Migrating from old storage system to new storage system]
