---
permalink: linux-administration/concept_error_message_locations.html
sidebar: sidebar
keywords: 
summary: 'SnapDrive for UNIX provides information about error messages as command output and in various log files.'
---
= Error message locations
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX provides information about error messages as command output and in various log files.

SnapDrive for UNIX provides information about error messages in the following places:

* The command output
+
It displays all messages to the standard error output of the SnapDrive for UNIX command.

* The system log
+
SnapDrive for UNIX logs all errors that have a severity level of Fatal and Admin error to the system log using the syslog(3) mechanism.

* The audit log file
+
The audit log records the following information for each SnapDrive for UNIX command:

 ** Who issued it
 ** When it was issued
 ** What its exit status was.
+
This is very useful in determining what actually happened on a system.

* The trace log file
+
The trace log records more detailed information about any errors that occur. NetApp Technical support uses this log when diagnosing problems.
