---
permalink: linux-administration/task_estimating_the_storage_space_to_split_a_lun_clone.html
sidebar: sidebar
keywords: snap, snapdrive, lun, clone, split, storage, space,
summary: The clone split estimation helps you to estimate the required storage space \(in MB\) to split a LUN clone. Depending on the clone split estimation provided by SnapDrive for UNIX, you can determine the space availability to split a LUN clone.
---
= Estimating the storage space to split a LUN clone
:icons: font
:imagesdir: ../media/

[.lead]
The clone split estimation helps you to estimate the required storage space (in MB) to split a LUN clone. Depending on the clone split estimation provided by SnapDrive for UNIX, you can determine the space availability to split a LUN clone.

.Steps

. Enter the following command to estimate the required storage space to split a LUN clone.
+
`*snapdrive clone split estimate [-lun]_long_lun_name_ [_long_lun_name..._] | [{-dg | -vg | -fs | -hostvol | -lvol}_file_spec_ [_file_spec..._]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose]*`
+
This operation displays the following information:

 ** Resource name
 ** Container- Volume for a LUN clone
 ** Required Space - space required to split a LUN clone
 ** Available space - space available on the container
 ** Storage Status - indicates the space availability for a LUN clone split
 ** Owned Space - space occupied by the LUN clone
 ** Shared Space - space occupied by the LUN clone along with the parent

+
The `Owned Space` and `Shared Space` is displayed when you use `-verbose` option.

The following example estimates the storage space to split a LUN clone.

----
# snapdrive clone split estimate -fs /mnt/my_mnt1
Resource     Container Required Available Storage
                       Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  5120    9986    AVAILABLE
             -112:/vol/vol_1
----

The following is an example of using the `-verbose` option. Alternatively, you can use `-v` option.

----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container  Owned    Shared   Required Available Storage
                       Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  365   403      5120     9986 AVAILABLE
             -112:/vol/vol_1
----
