---
permalink: linux-administration/task_adding_sd_hostname_to_the_storage_system.html
sidebar: sidebar
keywords: snap, snapdrive, sd, hostname, storage, manager, operations, administrator
summary: 'The Operations Manager console administrator can create the sd-hostname user on the storage system using Operations Manager console. After the steps are completed, the Operations Manager console administrator must manually send the credentials to the SnapDrive for UNIX administrator. You can use any name in place of sd-hostname; however it is best to use sd-hostname.'
---
= Adding sd-hostname to the storage system
:icons: font
:imagesdir: ../media/

[.lead]
The Operations Manager console administrator can create the sd-hostname user on the storage system using Operations Manager console. After the steps are completed, the Operations Manager console administrator must manually send the credentials to the SnapDrive for UNIX administrator. You can use any name in place of sd-hostname; however it is best to use sd-hostname.

. Obtain the root password of the storage system and store the password.
+
To add the password for the storage system, select *Management* > *Storage System*.

. Create an sd-hostname user for each UNIX system.
. Assign capabilities `api-*` and `login-*` to a role, such as sd-role.
. Include this role (sd-role) in a new usergroup, such as sd-usergroup.
. Associate this usergroup (sd-usergroup) with the sd-hostname user on the storage system.
