---
permalink: linux-administration/task_verifying_the_status_of_clone_split.html
sidebar: sidebar
keywords: 
summary: 'You can query the clone split status by using a job ID or file specification. SnapDrive for UNIX indicates the current status of the clone split as in-progress, failed, or complete.'
---
= Viewing the status of a volume clone or LUN clone split
:icons: font
:imagesdir: ../media/

[.lead]
You can query the clone split status by using a job ID or file specification. SnapDrive for UNIX indicates the current status of the clone split as in-progress, failed, or complete.

. Enter the following command to query the clone split status using a job ID or file specification. snapdrive clone split status [-lun]long_lun_name [long_lun_name...] [{-dg | -vg | -fs | -hostvol | -lvol}file_spec [file_spec...]][-job <jobid> ] [-all]

The following example shows the clone split status using a job ID.

----
# snapdrive clone split status -job SVE2oxKXzH
Clone-Split-Status for /fs1-1_3 is 1% Complete
Clone-Split-Status for /fs1_0 is 73% Complete
Clone-Split-Status for /fs1_1 is 73% Complete
Clone-Split-Status for /fs1_2 is 74% Complete
Clone-Split-Status for /fs1_3 is 1% Complete
----

NOTE: You can check the status of a clone split progress in either of the following ways:

* You can verify the clone by using the snapdrive storage show -fs /mnt/my_mnt or snapdrive storage show -lunlong_lun_pathname commands. In either case, the clone type is displayed as a FlexClone or LUN clone if the split has not been completed.
* You can verify the clone split progress state by logging into the storage system and using the following commands in the storage system CLI: vol clone split statusvol_namelun clone split status lun_name

The following example shows a clone split status query made using the file specification:

----
# snapdrive clone split status -fs /mnt/my_mnt3 -fs /mnt/my_mnt4
Clone-Split-Status for /mnt/my_mnt3 is 14% Complete
Clone-Split-Status for /mnt/my_mnt4 is 17% Complete
----

The following example shows a clone split status query that is running:

----
# snapdrive clone split status -all
Job ID: SVE2oxKXzH:
Clone-Split-Status for /fs1-1_3 is 100% Complete
Clone-Split-Status for /fs1_0 is 100% Complete
Clone-Split-Status for /fs1_1 is 100% Complete
Clone-Split-Status for /fs1_2 is 100% Complete
Clone-Split-Status for /fs1_3 is 100% Complete
----

* When a job is removed from the job set and you query the status of a clone split status using file specification, SnapDrive for UNIX displays the error message as No split is currently in progress for the given resource.
* When a job is removed from the job set and you query the status of a clone split using a job ID, SnapDrive for UNIX displays the error message as Job ID is not valid.
* When all file specifications are removed from a job and you query the status of a clone split using the Job ID, SnapDrive for UNIX displays as Job ID is not valid because the job is removed from the job set.
* If any file specifications fail due to insufficient space in the storage system, the job still continues to split for the remaining file specifications. This means the job is not deleted from the job queue and the job status is retained until you query the overall job result.
