---
permalink: linux-administration/task_specifying_login_information.html
sidebar: sidebar
keywords: snap, snapdrive, login, user, password
summary: 'You must specify the user login information for a storage system. Depending on what you specified when you set up the storage system, each storage system could use either the same user name or password or a unique user name or password. If all the storage systems use the same user name or password information, you must perform the following steps once. If the storage systems use unique user names or passwords, you must repeat the following steps for each storage system.'
---
= Specifying login information
:icons: font
:imagesdir: ../media/

[.lead]
You must specify the user login information for a storage system. Depending on what you specified when you set up the storage system, each storage system could use either the same user name or password or a unique user name or password. If all the storage systems use the same user name or password information, you must perform the following steps once. If the storage systems use unique user names or passwords, you must repeat the following steps for each storage system.

Ensure that you are logged in as a root user.

.Steps

. Enter the following command:
+
`*snapdrive config set _user_name filername_ [_filername..._]*`
+
`_user_name_` is the user name that was specified for that storage system when you first set it up.
+
`_filername_` is the name of the storage system.
+
`_[filername...]_` defines that you can enter multiple storage system names on one command line if they all have the same user login or password. You must enter the name of at least one storage system.

. At the prompt, enter the password, if there is one.
+
NOTE: If no password was set, press Enter (the null value) when prompted for a password.
+
This example sets up a user called `root` for a storage system called toaster:
+
----
# snapdrive config set root toaster
Password for root:
Retype Password:
----
+
This example sets up one user called `root` for three storage systems:
+
----
# snapdrive config set root toaster oven broiler
Password for root:
Retype Password:
----

. If you have another storage system with a different user name or password, repeat these steps.
