---
permalink: linux-administration/task_stopping_the_clone_and_lun_clone_split.html
sidebar: sidebar
keywords: snap, snapdrive, clone, split, lun, volume, specification
summary: 'You can stop the clone split for a volume clone or LUN clone using the job ID or file specification.'
---
= Stopping the volume clone or LUN clone split operation
:icons: font
:imagesdir: ../media/

[.lead]
You can stop the clone split for a volume clone or LUN clone using the job ID or file specification.

.Steps

. Enter the following command:
+
snapdrive clone split stop [-lun] long_lun_name [long_lun_name...] |[{-dg | -vg | -fs | -hostvol | -lvol} file_spec [file_spec...]] | [-job <jobid>]
+
SnapDrive for UNIX stops the clone split stop operation that is in progress.

The following example shows the clone split operation that is stopped by using the file specification.

----
# snapdrive clone split stop -fs /mnt/my_mnt4 /mnt/my_mnt3
Clone-Split for "/mnt/my_mnt4" is 0% Completed and Stopped.
Clone-Split for "/mnt/my_mnt3" is 0% Completed and Stopped.
----

The following example shows the clone split operation that is stopped by using the job ID.

----
# snapdrive clone split stop -job B265Dbv8gh
Clone-Split for "/mnt/my_mnt3" is 14% Completed and Stopped.
Clone-Split for "/mnt/my_mnt4" is 17% Completed and Stopped.
----

The following example is a typical output that shows the clone split stop operation for a file specification that is already stopped.

----
# snapdrive clone split stop -fs /mnt/my_mnt4 /mnt/my_mnt3
Clone-Split for "/mnt/my_mnt3" is not stopped : No split is in progress for this resource
Clone-Split for "/mnt/my_mnt4" is not stopped : No split is in progress for this resource
----

[NOTE]
====
* If the clone split is stopped for a particular file specification in the job id and the clone split stop is successful, then file specification is removed from the job.
* If the clone split is stopped for a job, and the clone split stop is successful for all the file specification in the job, the job is removed from the job set.
====
