---
permalink: linux-administration/task_creating_a_filesystem_on_a_lunand_specifying_thelun.html
sidebar: sidebar
keywords: 
summary: 'You can create a file system on a LUN and specify the LUNs that are created as a part of it.'
---
= Creating a file system on a LUN and specifying the LUN
:icons: font
:imagesdir: ../media/

[.lead]
You can create a file system on a LUN and specify the LUNs that are created as a part of it.

. Use the following command format to complete this operation: snapdrive storage create -fsfile_spec -nolvm [-fstype type] [-vmtype type] [-fsopts options] [-mntopts options] [-nopersist] -lun long_lun_name -lunsize sizeig_name [ig_name...]] [{ -reserve | -noreserve }]
+
SnapDrive for UNIX creates the file system on the storage system, volume, and LUN you specify. It performs all of the tasks associated with host preparation and discovery for the LUNs, as well as mapping and connecting the LUNs to the host entity.

== Example: Creating a 100 MB file system on luna in acctfiler:/vol/vol1

# snapdrive storage create -fs /mnt/acct1 -lun acctfiler:/vol/vol1/luna -lunsize 100m -nolvm
