---
permalink: linux-administration/task_enabling_multipathing.html
sidebar: sidebar
keywords: SnapDrive for UNIX
summary: 'To use multipathing in SnapDrive for UNIX, you must complete steps that include installing and starting the HBA. If you are using a non-NetApp multipathing solution, you must download the software and application package from the HBA vendor’s web site.'
---
= Enabling multipathing
:icons: font
:imagesdir: ../media/

[.lead]
To use multipathing in SnapDrive for UNIX, you must complete steps that include installing and starting the HBA. If you are using a non-NetApp multipathing solution, you must download the software and application package from the HBA vendor's web site.

Your system must be running current versions of FC and iSCSI system components.

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

. Install the supported HBAs before you install the appropriate Host Utilities software.
+
NOTE: SnapDrive for UNIX supports multivendor HBAs.

. Start the HBA service.
+
If the HBA service is not running, the following error message is displayed when you run SnapDrive for UNIX commands, such as snapdrive storage create and snapdrive config prepare luns:
+
----
0001-876 Admin error: HBA assistant not found
----
+
You must verify that the required number of paths are up and running. You can verify the paths by using the sanlun utility, which is included with the Host Utilities software. For example, in the FC multipathing configuration, you can use the sanlun fcp show adapter -v command.
+
In the following example, there are two HBA ports (fcd0 and fcd1) connected to the host that are operational (port state). You can have only one HBA or iSCSI initiator and you must configure multipathing by providing more than one path to the target LUNs.
+
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
If multipathing is enabled on a host, multiple paths are visible for the same LUN. You can use the sanlun lun show all command to verify the paths. In the following example, you can find multiple paths to the same LUN (fish: /vol/vol1/lun):
+
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----

. If a third-party multipathing solution is supported by SnapDrive for UNIX or Host Utilities, download the HBA driver software package and application package from the HBA vendor's web site.*QLogic*: For QLogic HBAs, go to http://support.qlogic.com/. From OEM models, select NetApp. Locate the driver version listed in the support Matrix and download it. *Emulex:* For Emulex HBAs, go to http://www.emulex.com/ts/index.html. From Downloads, select NetApp. Locate the driver version listed in the support Matrix and download it. Also download the Emulex applications package from the same location.
+
If you are using a QLogic adapter with FC connectivity, download the QLogic rescan script from the QLogic web site and copy it to the /root path (for example, /root/dynamic-lun-rescan.sh). The QLogic rescan script asks for user confirmation; SnapDrive for UNIX might hang indefinitely at this confirmation stage. You can avoid this confirmation by setting the variable QL_DISABLE_WARNING to 1 in the script.
+
Earlier versions of SnapDrive for UNIX used vendor-specific SCSI rescan scripts to scan LUNs over FC, and thereby copying vendor-specific script to /root/dynamic-lun-rescan.sh. This was made available until RHEL 5U3.
+
For RHEL 5U4/ SLES 10SP2 and later versions, the rescan script is currently available in the /usr/bin directory. In case the rescan script is not available in the directory, it is present along with the sg3_utils package.
+
NOTE: You must ensure that the sg3_utils and sg3_utils-libs libraries are available for Red Hat Enterprise Linux (RHEL) and Oracle Enterprise Linux (OEL) versions. However, the sg3_utils libraries are available for SUSE Linux Enterprise Server (SLES) version in the scsci utility.rpm package.

. In an FC configuration, zone the host HBA ports and target ports by using the switch zoning configuration.
. Install and set up the appropriate FC switch.
. Check the SnapDrive for UNIX stack requirements.
. Install or upgrade SnapDrive for UNIX.
. Verify the SnapDrive for UNIX installation.
. Locate the snapdrive.conf file path.
. Configure the following configuration variables in the snapdrive.conf file:
 ** multipathing-type
 ** default-transport
 ** fstype
 ** vmtype
For every host, the multipathing type, transport type, file system, and volume manager type are dependent on each other. The following table describes all the possible combinations:

+
|===
| Host platform| Default transport type| Multipathing type| fstype| vmtype
a|
Linux
a|
iscsi
a|
nativempio
a|
ext4 or ext3
a|
lvm
a|
iscsi
a|
none
a|
ext4 or ext3
a|
lvm
a|
FCP
a|
none
a|
ext4 or ext3
a|
lvm
a|
FCP
a|
nativempio
a|
ext4 or ext3
a|
lvm
|===
The preceding table gives the supported values of the multipathing-type, default-transport, fstype, and vmtype configuration variables.
+
NOTE: If the transport protocol is iSCSI, and the multipathing type is set as none, you should stop the multipath daemon and execute SnapDrive for UNIX commands.
. Save the snapdrive.conf file.
+
SnapDrive for UNIX automatically checks this file each time it starts. You must restart the SnapDrive for UNIX daemon for the changes to take effect.

*Related information*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[SnapRestore and Snapconnect operations does not work in Linux after multipathing type migration]

http://mysupport.netapp.com[NetApp Support]

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936[Linux Unified Host Utilities 7.1 Installation Guide]
