---
permalink: linux-installation-7mode/task_connecting_linux_host_to_the_storage_system.html
sidebar: sidebar
keywords: SnapDrive for UNIX
summary: 'For successful SnapDrive for UNIX operations, you must set up your storage system before connecting it to the Linux host.'
---
= Connecting Linux hosts to storage systems
:icons: font
:imagesdir: ../media/

[.lead]
For successful SnapDrive for UNIX operations, you must set up your storage system before connecting it to the Linux host.

The storage system name must be registered with a Domain Name Service (DNS) server in your network or in the `/etc/hosts` file.

.Steps

. Create a user on the storage system:
+
`*snapdrive config set _user_name storage_system_name_*`

. View the users associated with the storage system and get the user name or storage system pair details:
+
`*snapdrive config list*`
+
The command displays the user name or the storage system pairs for all systems that have the users specified within SnapDrive for UNIX.

. If the storage system has multiple data interfaces, configure the data interface for the new management interface: 
+
`*snapdrive config set -mgmtpath _management_interface_path data_interface_path_*`

. Verify that all data and management interfaces are configured properly:
+
`*snapdrive config list -mgmtpath*`
