---
permalink: linux-installation-7mode/task_connecting_linux_host_to_the_storage_system.html
sidebar: sidebar
keywords: SnapDrive for UNIX
summary: 'For successful SnapDrive for UNIX operations, you must set up your storage system before connecting it to the Linux host.'
---
= Connecting Linux hosts to storage systems
:icons: font
:imagesdir: ../media/

[.lead]
For successful SnapDrive for UNIX operations, you must set up your storage system before connecting it to the Linux host.

The storage system name must be registered with a Domain Name Service (DNS) server in your network or in the /etc/hosts file.

. Create a user on the storage system: snapdrive config set user_namestorage_system_name
. View the users associated with the storage system and get the user name or storage system pair details: snapdrive config list
+
The command displays the user name or the storage system pairs for all systems that have the users specified within SnapDrive for UNIX.

. If the storage system has multiple data interfaces, configure the data interface for the new management interface: snapdrive config set -mgmtpath management_interface_pathdata_interface_path
. Verify that all data and management interfaces are configured properly: snapdrive config list -mgmtpath
