---
permalink: aix/concept_operation_with_multiple_storage_objects.html
sidebar: sidebar
keywords: 
summary: 'The following example shows the error message you would receive when you are not an authorized user to carry out the specific operation.'
---
= Operation with multiple storage objects
:icons: font
:imagesdir: ../media/

[.lead]
The following example shows the error message you would receive when you are not an authorized user to carry out the specific operation.

----
[john]$ snapdrive storage show –all

Connected LUNs and devices:

device filename   adapter  path  size  proto  state  clone  lun path                           backing Snapshot
----------------  -------  ----  ----  -----  -----  -----  --------                           ---------------
/dev/sdao            -     -     200m  iscsi  online  No    storage_array1:/vol/vol2/passlun1           -
/dev/sda1            -     -     200m  fcp    online  No    storage_array1:/vol/vol2/passlun2           -

Host devices and file systems:

dg: testfs1_SdDg                dgtype lvm
hostvol: /dev/mapper/testfs1_SdDg-testfs1_SdHv  state: AVAIL
fs: /dev/mapper/testfs1_SdDg-testfs1_SdHv       mount point: /mnt/testfs1 (persistent) fstype jfs2

device filename   adapter  path  size  proto  state   clone  lun path                                backing Snapshot
----------------  -------  ----  ----  -----  -----   -----  --------                                ---------
/dev/sdn             -      P    108m  iscsi  online   No    storage_array1:/vol/vol2/testfs1_SdLun         -
/dev/sdn1             -      P    108m  fcp  online   No    storage_array1:/vol/vol2/testfs1_SdLun1         -

0002-719 Warning: SD.Storage.Read access denied on volume storage_array1:/vol/vol1 for user unix_host\john on Operations Manager server ops_mngr_server
----

John is authorized to list storage entities on vol2 but not on vol1. SnapDrive for UNIX displays entities of vol1 and displays a warning message for vol2.

NOTE: For storage list, storage show, snap list, and snap show commands SnapDrive for UNIX displays a warning instead of error.
