---
permalink: aix/concept_operating_system_limits_on_open_files.html
sidebar: sidebar
keywords: snap, snapdrive, operating, system, limit, open, files
summary: SnapDrive for UNIX checks for the number of files opened simultaneously. If it crosses the limit, SnapDrive for UNIX throws an error.
---
= Operating system limits on open files
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX checks for the number of files opened simultaneously. If it crosses the limit, SnapDrive for UNIX throws an error.

SnapDrive for UNIX checks for operating system limitations on the number of files opened by a process.

NOTE: The default limit for the number of file handles opened simultaneously by one process varies based on your operating system. Check your operating system documentation to determine the limit.

If the number of open LUNs for one operation exceeds the operating system limit on the number of file handles opened simultaneously by one process, SnapDrive for UNIX exits with the following error message:

`0001-001 Admin error: Unable to open device path-to-device`
