---
permalink: aix/concept_snapdrive_for_unix_provisioning_in_an_lvma_vxvm_environment.html
sidebar: sidebar
keywords: snap, snapdrive, lvm, provisioning, environment
summary: SnapDrive for UNIX storage commands provision LVM entities by creating LVM objects.
---
= SnapDrive for UNIX provisioning in an LVM environment
:icons: font
:imagesdir: ../media/

SnapDrive for UNIX storage commands provision LVM entities by creating LVM objects.

If you request a SnapDrive for UNIX storage operation that provisions an LVM entity--for example, a disk group that includes host volumes or file systems--the `snapdrive storage` command works with the LVM to create the LVM objects and file systems that use the storage.

During storage provisioning operation, the following actions occur:

* The host LVM combines LUNs from a storage system into disks, or volume groups.
+
The storage is then divided into logical volumes, which are used as if they were raw disk devices to hold file systems or raw data.

* SnapDrive for UNIX integrates with the host LVM to determine which NetApp LUNs make up each disk group, host volume, and file system requested for a Snapshot copy.
+
Because the data from any specified host volume can be distributed across all disks in the disk group, Snapshot copies can be made and restored only for whole disk groups.
