---
permalink: aix/reference_error_message_values.html
sidebar: sidebar
keywords: snap, snapdrive, error, message, value
summary: It is helpful for you to be aware of some of the more common error messages that you might see when using SnapDrive for UNIX, and to know how to address them.
---
= Error message values
:icons: font
:imagesdir: ../media/

[.lead]
It is helpful for you to be aware of some of the more common error messages that you might see when using SnapDrive for UNIX, and to know how to address them.

The following table gives you detailed information about the most common errors that you might encounter when using SnapDrive for UNIX:

[cols=5*,options="header",cols-"10,10,10,35,35"]
|===
| Error code | Return code | Type | Message | Solution
| 0000-001 | NA | Admin | Datapath has been configured for the storage system <STORAGE-SYSTEM-NAME>. Please delete it using snapdrive config delete -mgmtpath command and retry. | Before deleting the storage system, delete the management path configured for the storage system by using the `snapdrive config delete -mgmtpath` command.
|===
*Related information*

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223[AIX Host Utilities 6.0 Installation and Setup Guide]
