---
permalink: aix/reference_host_side_command_lines.html
sidebar: sidebar
keywords: snap, snapdrive, host, side, command, line
summary: SnapDrive for UNIX commands are used for host-side operations.
---
= Host-side command lines
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX commands are used for host-side operations.

The following table gives various command-line options for host-side operations.

[options="header"]
|===
| Operation| Command-line option
.3+a|
Host connect
a|
`snapdrive host connect -lun _long_lun_name_ [_lun_name ..._] [-vmtype _type_]`
a|
`snapdrive host connect -fs _file_spec_ -nolvm -lun _long_lun_name_ [-nopersist][-mntopts options] [-fstype _type_] [-vmtype _type_]`
a|
`snapdrive host connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name_][-nopersist] [-mntopts _options_][-vmtype _type_]`
.2+a|
Host disconnect
a|
`snapdrive host disconnect-lun _long_lun_name_ [_lun_name..._] [-vmtype _type_]`
a|
`snapdrive host disconnect {-vg \| -dg \| -fs \| -lvol \| -hostvol} _file_spec_[_file_spec ..._][{-vg \| -dg \| -fs \| -lvol \| -hostvol} _file_spec_ [_file_spec ..._]...] [-full] [-fstype _type_] [-vmtype _type_]`
|===
