---
permalink: aix/task_enabling_multipathing.html
sidebar: sidebar
keywords: snap, snapdrive, enable, multipathing, hba
summary: To use multipathing in SnapDrive for UNIX, you must complete steps that include installing and starting the HBA. If you are using a non-NetApp multipathing solution, you must download the software and application package from the HBA vendor’s web site.
---
= Enabling multipathing
:icons: font
:imagesdir: ../media/

[.lead]
To use multipathing in SnapDrive for UNIX, you must complete steps that include installing and starting the HBA. If you are using a non-NetApp multipathing solution, you must download the software and application package from the HBA vendor's web site.

Your system must be running current versions of FC and iSCSI system components.

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

.Steps

. Install the supported HBAs before you install the appropriate Host Utilities software.
+
NOTE: SnapDrive for UNIX supports multivendor HBAs.

. Start the HBA service.
+
If the HBA service is not running, the following error message is displayed when you run SnapDrive for UNIX commands, such as `snapdrive storage create` and `snapdrive config prepare luns`:
+
----
0001-876 Admin error: HBA assistant not found
----
+
You must verify that the required number of paths are up and running. You can verify the paths by using the sanlun utility, which is included with the Host Utilities software. For example, in the FC multipathing configuration, you can use the `sanlun fcp show adapter -v` command.
+
In the following example, there are two HBA ports (fcd0 and fcd1) connected to the host that are operational (port state). You can have only one HBA or iSCSI initiator and you must configure multipathing by providing more than one path to the target LUNs.
+
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
If multipathing is enabled on a host, multiple paths are visible for the same LUN. You can use the `sanlun lun show all` command to verify the paths. In the following example, you can find multiple paths to the same LUN (`fish: /vol/vol1/lun`):
+
----
filer:         lun-pathname        device filename  adapter    protocol   lun size              lun state
    filer_1:        fish/vol/vol1/l1      hdisk36          fcs0       FCP       5m   (5242880)        GOOD
    filer_2:        fish/vol/vol0/lunKr   hdisk39          fcs0       FCP       100m (104857600)      GOOD
    filer_3:        fish/vol/vol0/testaix hdisk2           fcs0       FCP       200m (209715200)      GOOD
    filer_4:        fish/vol/vol1/l1      hdisk45          fcs1       FCP       5m   (5242880)        GOOD
----

. In an FC configuration, zone the host HBA ports and target ports by using the switch zoning configuration.
. Install and set up the appropriate FC or iSCSI switch.
. Check the SnapDrive for UNIX stack requirements.
. Install or upgrade SnapDrive for UNIX.
. Verify the SnapDrive for UNIX installation.
. Locate the `snapdrive.conf` file path.
. Configure the following configuration variables in the `snapdrive.conf` file:
 ** `_multipathing-type_`
 ** `_default-transport_`
 ** `_fstype_`
 ** `_vmtype_`

+
For every host, the multipathing type, transport type, file system, and volume manager type are dependent on each other. The following table describes all the possible combinations:

+
[options="header"]
|===
| Host platform| Default transport type| Multipathing type| fstype| vmtype
.3+a|
AIX
.3+a|
FCP
a|
absolute
a|
jfs2 or jfs
a|
lvm
a|
nativempio
a|
jfs2 or jfs
a|
lvm
a|
dmp
a|
vxfs
a|
vxvm
|===
The preceding table gives the supported values of the `_multipathing-type_`, `_default-transport_`, `_fstype_`, and `_vmtype_` configuration variables.
. Save the `snapdrive.conf` file.
+
SnapDrive for UNIX automatically checks this file each time it starts. You must restart the SnapDrive for UNIX daemon for the changes to take effect.

*Related information*

http://mysupport.netapp.com[NetApp Support]

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223[AIX Host Utilities 6.0 Installation and Setup Guide]
