---
permalink: aix/task_disconnectingsnapshot_copy_withstorage_entities.html
sidebar: sidebar
keywords: snap, snapdrive, disconnect, command, snapshot, storage
summary: You can use the snapdrive snap disconnect command to disconnect a Snapshot copy that contains storage entities.
---
= Disconnecting Snapshot copy with storage entities
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `snapdrive snap disconnect` command to disconnect a Snapshot copy that contains storage entities.

.Steps

. Enter the following command:
+
`*snapdrive snap disconnect {-dg | -fs | -hostvol} _file_spec_ [_file_spec..._]{-dg | -fs | -hostvol} file_spec [file_spec...]] [-full] [-fstype type] [-vmtype type] [-split]*`
+
This command must always start with the storage entity, for example, `-lun`, `-dg`, `-hostvol`, or `-fs`.

 ** If you specify a LUN (`-lun`), you must enter the long LUN name. You cannot specify a LUN with the `-lun` option on the same command line as other storage entities (`-vg`, `-dg`, `-fs`, `-lvol`, or `-hostvol` options).
 ** If you specify an NFS mountpoint, you cannot specify non-NFS entities (`-vg`, `-dg`, `-fs`, `-lvol`, or `-hostvol`) on the same command line. You must use a separate command to specify the NFS mountpoint.

NOTE: An error message occurs if the host entity is using LUNs that are not part of the Snapshot copy. An error also occurs if you specify a subset of the host volumes and/or file systems contained in each target disk group.

SnapDrive for UNIX removes the mappings for the storage entities specified in the command line.

This command line removes the mappings to all the LUNs underlying the host volume dg5/myvolume. It removes any temporary LUNs that creates with a Snapshot connect operation:

----
# snapdrive snap disconnect -hostvol dg5/myvolume
----

This command line removes the mappings to all the LUNs underlying the host volume dg5/myvolume. It removes any temporary LUNs that creates with a Snapshot connect operation:

----
# snapdrive snap disconnect -hostvol dg5/myvolume
----

This command disconnects the mapping to disk group 1 (dg1) and to the underlying LUN. It also removes any temporary LUNs that creates with the Snapshot connect operation:

----
# snapdrive snap disconnect -lun toaster:/vol/vol1/luna -dg dg1
----

This command line removes the mapping to the file system fs1, and to the LUN that underlies it. It also removes any temporary LUNs that creates with the Snapshot connect operation:

----
# snapdrive snap disconnect -fs mnt/fs1
----

This command line removes the mappings for disk groups dg1, dg2, and dg3. It removes any temporary LUNs that creates with the Snapshot connect operation:

----
# snapdrive snap disconnect -dg dg1 dg2 dg3
----

This example disconnects a Snapshot copy with file system, disk group on Veritas stack:

----
# snapdrive snap disconnect -fs /mnt/fs1_clone -fstype vxfs
delete file system /mnt/fs1_clone
- fs /mnt/fs1_clone ... deleted
- hostvol vxvm1_0/fs1_SdHv_0 ... deleted
- dg vxvm1_0 ... deleted
- LUN snoopy:/vol/vol1/lunVxvm1_0 ... deleted
----

This example disconnects a Snapshot copy with file system, disk group on LVM stack:

----
# snapdrive snap disconnect -fs /mnt/fs1_clone -fstype jfs2

delete file system /mnt/fs1_clone
- fs /mnt/fs1_clone ... deleted
- hostvol lvm1_0/fs1_SdHv_0 ... deleted
- dg lvm1_0 ... deleted
- LUN snoopy:/vol/vol1/lunLvm1_0 ... deleted
----
