---
permalink: aix/task_configuring_user_credentials_on_snapdrive_for_unix.html
sidebar: sidebar
keywords: 
summary: 'The SnapDrive for UNIX administrator receives user credentials from Operations Manager console administrator. These user credentials need to be configured on SnapDrive for UNIX for proper storage operations.'
---
= Configuring user credentials on SnapDrive for UNIX
:icons: font
:imagesdir: ../media/

[.lead]
The SnapDrive for UNIX administrator receives user credentials from Operations Manager console administrator. These user credentials need to be configured on SnapDrive for UNIX for proper storage operations.

. Configure sd-admin on the storage system.
+
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----

. Configure sd-hostname on the storage system.
+
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----

. Verify step 1 and step 2, using the snapdrive config list command.
+
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----

. Configure SnapDrive for UNIX to use Operations Manager console Role-based access control (RBAC) by setting the configuration variable rbac-method="dfm" in the snapdrive.conf file.
+
NOTE: The user credentials are encrypted and saved in the existing .sdupw file. The default location of the earlier file is /opt/NetApp/snapdrive/.sdupw.
