---
permalink: aix/task_creating_a_filesystem_on_a_lunand_specifying_thelun.html
sidebar: sidebar
keywords:
summary: 'You can create a file system on a LUN and specify the LUNs that are created as a part of it.'
---
= Creating a file system on a LUN and specifying the LUN
:icons: font
:imagesdir: ../media/

[.lead]
You can create a file system on a LUN and specify the LUNs that are created as a part of it.

.Steps

. Use the following command format to complete this operation:
+
`*snapdrive storage create -fs _file_spec_ -nolvm [-fstype _type_] [-vmtype _type_] [-fsopts _options_] [-mntopts _options_] [-nopersist] -lun _long_lun_name_ -lunsize _size ig_name_ [_ig_name..._]] [{ -reserve | -noreserve }]*`
+
SnapDrive for UNIX creates the file system on the storage system, volume, and LUN you specify. It performs all of the tasks associated with host preparation and discovery for the LUNs, as well as mapping and connecting the LUNs to the host entity.

== Example: Creating a 100 MB file system on luna in acctfiler:/vol/vol1
`# snapdrive storage create -fs /mnt/acct1 -lun acctfiler:/vol/vol1/luna -lunsize 100m -nolvm`

*Example:* This example creates a JFS2 file system on a raw LUN, on an AIX host: `# snapdrive storage create -fs /mnt/jfs1 -fstype jfs2 -lun snoopy:/vol/vol1/lunLvm1 -lunsize 100m -nolvm`

----
LUN snoopy:/vol/vol1/lunLvm1 ... created
mapping new lun(s) ... done
discovering new lun(s) ... done
LUN to device file mappings:
- snoopy:/vol/vol1/lunLvm1 => /dev/hdisk2
172 Creating storage
file system /mnt/jfs1 created
----
