---
permalink: solaris/concept_renaming_asnapshot_copy_thatspans_storage_systems_orvolumes.html
sidebar: sidebar
keywords: 
summary: 'For Snapshot copies that cross multiple storage systems or storage system volumes, rename all the related Snapshot copies.'
---
= Renaming a Snapshot copy that spans storage systems or volumes
:icons: font
:imagesdir: ../media/

[.lead]
For Snapshot copies that cross multiple storage systems or storage system volumes, rename all the related Snapshot copies.

You can also use this command to rename a Snapshot copy that is across multiple storage systems or multiple storage system volumes.

If you rename one of these Snapshot copies, you must also rename all the related Snapshot copies using the same name. This is because SnapDrive for UNIX uses a short name when it creates the Snapshot copy, even though it spans multiple storage systems or volumes. The rename command changes the name of the current Snapshot copy but it does not change the name of the related Snapshot copies in the other locations.
