---
permalink: solaris/concept_informationrequired_forusing_the_snapdrive_snapdisconnect_command.html
sidebar: sidebar
keywords:
summary: 'To disconnect a Snapshot copy, specify the type of storage entity to be used, such as, LUN, disk groups, file systems, or host volume.'
---
= Information required for using the snapdrive snap disconnect command
:icons: font
:imagesdir: ../media/

[.lead]
To disconnect a Snapshot copy, specify the type of storage entity to be used, such as, LUN, disk groups, file systems, or host volume.

The following table gives the information you need to supply when you use the `snapdrive snap disconnect` command.

[options="header"]
|===
| Requirement/Option| Argument
a|
LUN (-lun `_file_spec_`)
a|
_name of the LUN. Include the name of the filer, volume and LUN._

a|
Disk group (-dg `_file_spec_` ) or volume group (-vg `_file_spec_` )
a|
_name of the disk or volume group_
a|
File system (-fs `_file_spec_` )
a|
`_filesystem_name_`
a|
Host volume (-hostvol `_file_spec_` ) or logical volume (-lvol `_file_spec_` )
a|
_name of the host or logical volume_
2+a|
Specify the type of storage entity that you want to use to disconnect the Snapshot copy and supply that entity's name with the appropriate argument.

This is the value for the `_file_spec_` argument.

a|
`-devicetype~`
a|
~
2+a|
Optional: Specifies the type of device to be used for SnapDrive for UNIX operations. This can be either "`shared`" that specifies the scope of LUN, disk group, and file system as host cluster-wide or "`dedicated`" that specifies the scope of LUN, disk group, and file system as local.

If you specify the `-devicetype dedicated` option, all the options of the `snapdrive snap disconnect` command currently supported in SnapDrive 2.1 for UNIX function as they always have.

If you initiate the `snapdrive snap disconnect` command with the `-devicetype` shared option from any nonmaster node in the host cluster, the command is shipped to the master node and executed. For this to happen, you must ensure that the `rsh` or `ssh` access without password prompt for the root user should be configured for all nodes in the host cluster.

a|
`-full`
a|
~
2+a|
Include the -full option on the command line if you want SnapDrive for UNIX to disconnect the objects from the Snapshot copy even if a host-side entity on the command line has other entities (such as a disk group that has one or more host volumes). If you do not include this option, you must specify only empty host-side entities.
a|
`-fstype`
a|
`_type_`
a|
`-vmtype`
a|
`_type_`
2+a|
Optional: Specify the type of file system and volume manager to be used.
a|
`-split`
a|
~
2+a|
Enables to split the cloned volumes or LUNs during Snapshot connect and Snapshot disconnect operations.

|===
