---
permalink: solaris/concept_guidelines_for_storage_create_operation_in_a_host_cluster_environment.html
sidebar: sidebar
keywords: 
summary: 'You should follow certain guidelines when you create storage in a host cluster environment.'
---
= Guidelines for storage create operation in a host cluster environment
:icons: font
:imagesdir: ../media/

[.lead]
You should follow certain guidelines when you create storage in a host cluster environment.

* You can execute the snapdrive storage create command from any node in the host cluster.
* For storage create operation to be successful neither should be true:
 ** The storage entities should not be present on any node in the host cluster.
 ** The LUNs should not be mapped to any node in the host cluster.
* You can create a storage entity on a specific node either by using the -devicetype dedicated or the -devicetype shared option. If you are creating a storage entity that is in a dedicated mode, you can omit the -devicetype option, because the default value is dedicated.
* Host cluster-wide storage creation of a file system is supported on disk groups that use Veritas volume manager with the Veritas file system (VxFS). This operation does not support on raw LUNs; the -nolvm option also does not support.
* The -igroup option is not supported in the storage create operation.
* The storage create operation fails if one of the following situation occurs:
 ** If any error message occurs during the process of creating a storage entity. SnapDrive for UNIX executes storage create operation from the master node in a host cluster. Before creating the shared storage entities, SnapDrive for UNIX creates LUNs, maps the LUNs to the master node, and then maps the LUNs to all the nonmaster nodes. SnapDrive for UNIX internally creates and manages the igroups for all the nodes.
 ** If a node in the host cluster shuts down and reboots before starting the host clustered volume manager (CVM), the shared disk group used by the LUNs should be discovered on the node. By default, the LUNs are visible if the FC port address is not changed; otherwise, you must map the LUNs using the snapdrive storage connect command.
