---
permalink: solaris/concept_postinstallation_checks.html
sidebar: sidebar
keywords:
summary: 'After the installation is complete, you must perform a few tasks to ensure that SnapDrive for UNIX is installed successfully.'
---
= Performing post-installation checks
:icons: font
:imagesdir: ../media/

[.lead]
After the installation is complete, you must perform a few tasks to ensure that SnapDrive for UNIX is installed successfully.

. Verify that the installation program has installed all the necessary files on your host.
. Confirm that the configuration variables in the `snapdrive.conf` file have the correct settings.
+
For the majority of these variables, the default values should be applicable.

. Supply SnapDrive for UNIX with the current storage system login information.
+
When you set up your storage system, you supplied a user login for it. SnapDrive for UNIX needs this login information to work with the storage system.

. To use role-based access control (RBAC), set the `_rbac-method=dfm_` variable in the `snapdrive.conf` file.
+
By default, SnapDrive 4.0 for UNIX and later accesses the storage systems using the root credentials. The RBAC functionality is not turned on.

. To use HTTPS for a secure connection with the storage system and daemon service, set the `_use-https-to-sdu-daemon=on_` in the `snapdrive.conf` file.
+
NOTE: SnapDrive 5.0 for UNIX and later versions support HTTPS for daemon communication. By default, the option is set to `off`.

. Install the server certificate that is used by SnapDrive for UNIX in the
+
`sdu-daemon-certificate-path=/opt/NTAPsnapdrive/snapdrive.pem` path as specified in the `snapdrive.conf` file.

. Change the default password for the SnapDrive for UNIX daemon service by running the following command:
+
`*snapdrived passwd*`
. Check the details of the installed configuration components in `/var/log/sdconfcheck.out`.
