---
permalink: solaris/concept_informationrequired_forusing_the_snapdrive_storageconnect_command.html
sidebar: sidebar
keywords: snap, snapdrive, storage, connect, command
summary: There is some information that you need to supply when you use the snapdrive storage connect command. This information helps you to use the command correctly.
---
= Information required for using the snapdrive storage connect command
:icons: font
:imagesdir: ../media/

[.lead]
There is some information that you need to supply when you use the `snapdrive storage connect` command. This information helps you to use the command correctly.

[options="header"]
|===
| Requirement| Argument
2+a|
Specify the LUNs, the file system created directly on a LUN, or the LVM entity that you want to connect to the host.

* If you connect one or more LUNs, the first argument must use the long form of the LUN name, which specifies the storage system name, the volume name, and the name of the LUN within the volume.
+
To specify additional LUNs, you can use the LUN name alone if the new LUN is on the same storage system and volume as the previous LUN. Otherwise, you can specify a new storage system name and volume name (or just a volume name) to replace the previous values.

* If you connect a file system created directly on a LUN, you must include the long form of the LUN name, and also the `-nolvm` option.
* If you connect a LUN with a disk group, host volume, and file system, you must use the `-fs` and `-hostvol` options to specify the file system and host volume. The host volume must include the name of the disk group.

a|
A LUN (`-lun`)
a|
`_long_lun_name_`
2+a|
The first value you supply with the `-lun` option must include the storage system name, volume, and LUN name. To connect multiple LUNs on the same volume, you can use relative path names for the `-lun` option after you supply the complete information in the first path name. When SnapDrive for UNIX encounters a relative path name, it looks for the LUN on the same volume as the previous LUN. To connect additional LUNs that are not on the same volume, enter the full path name to each LUN.
a|
Additional LUNs
a|
`_lun_name_`(long or short form)
2+a|
The `_file_spec_` given to `-fs` is the name of the file system mountpoint when connecting a file system created directly on a LUN.
a|
A file system (`-fs file-spec`)
a|
`_filesystem_name_`
2+a|
To connect a file system that is created on a LUN without activating the host LVM.
a|
`-nolvm`
a|

2+a|
To connect a file system on a host volume:

The `-fs _file_spec_` and `-hostvol file_spec` you supply identify the LVM file system, disk group, and host volumes that you want to connect to a new host.

The storage hierarchy that you connect must contain a disk group, host volume, and file system. You must specify a value for `-fs` and `-hostvol`. The `-hostvol` value must include the name of the disk group.

a|
Host volume (`-hostvol file-spec`)
a|
`_disk_group_name_` and `_host_volume_name_`
2+a|
Optional: Use the `-nopersist` option to connect the storage to a new location without creating an entry in the host file system table. By default the storage connect command creates persistent mounts. This means that when you create an LVM storage entity on a Solaris host, SnapDrive for UNIX automatically creates the storage, mounts the file system and then places an entry for the file system in the host file system table.

a|
`-nopersist`
a|
~
2+a|
*Optional:* It is recommended that you use the default igroup for your host instead of supplying an igroup name.

a|
Igroup name (`-igroup`)
a|
`_ig_name_`
a|
`_-devicetype_`
a|
~
2+a|
To specify the type of device to be used for SnapDrive for UNIX operations. This can be either "`shared`" that specifies the scope of LUN, disk group, and file system as host cluster-wide or "`dedicated`" that specifies the scope of LUN, disk group, and file system as local.

a|
`-fstype`
a|
`_type_`
a|
`vmtype`
a|
`_type_`
2+a|
*Optional:* Specifies the type of file system and volume manager to be used for SnapDrive for UNIX operations.

a|
`-mntopts`
a|
~
2+a|
*Optional:* If you are creating a file system, you can specify the following options:

* Use `-mntopts` to specify options that you want to pass to the host mount command (for example, to specify host system logging behavior). The options you specify are stored in the host file system table file. Allowed options depend on the host file system type.
* The `_-mntopt_` argument is a file system `-type` option that is specified using the mount command `-o` flag. Do not include the `-o` flag in the `-mntopts` argument. For example, the sequence -mntopts tmplog passes the string `-o tmplog` to the `mount` command, and inserts the text tmplog on a new command line.
+
NOTE: If you pass any invalid `-mntopts` options for storage and snap operations, SnapDrive for UNIX does not validate those invalid mount options.

|===
