---
permalink: solaris/reference_storage_provisioning_command_lines.html
sidebar: sidebar
keywords: snap, snapdrive, storage, command, line, provisioning
summary: Some SnapDrive for UNIX commands are used for storage provisioning.
---
= Storage provisioning command lines
:icons: font
:imagesdir: ../media/

[.lead]
Some SnapDrive for UNIX commands are used for storage provisioning.

The following command-line options are used for storage-provisioning operations:

[options="header"]
|===
| Operation| Command-line option
.5+a|
Create
a|
`snapdrive storage create-lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [{ -dg \| -vg } _dg_name_] [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve \| -noreserve }][-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage create {-lvol \| -hostvol} _file_spec_ [{-dg \| -vg} dg_name]{-dgsize \| -vgsize} _size_-filervol _long_filer_path_ [-devicetype {shared \| dedicated}] [{-noreserve \| -reserve}] [-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage create -fs _file_spec_ -nolvm [-fsopts options ] [-mntopts options] [-nopersist] { -lun _long_lun_name_ \| -filervol _long_filer_path_ } -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve \| -noreserve }] [-devicetype {shared \| dedicated}] [-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage create _host_lvm_fspec_ -filervol _long_filer_path_ -dgsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve \| -noreserve }] [-devicetype {shared \| dedicated}]`
a|
`snapdrive storage create _host_lvm_fspec_ -lun _long_lun_name_ [_lun_name ..._] -lunsize _size_ [-igroup _ig_name_ [_ig_name ..._]] [{ -reserve \| -noreserve }]`

[NOTE]
====
You can use any one of the format for the `-file_spec` argument, depending on the type of storage you want to create. (Remember that `-dg` is a synonym for `-vg`, and `-hostvol` is a synonym for `-lvol`.)

To create a file system directly on a LUN, use this format: `-fs _file_spec_ [-nolvm -fs _type_] [-fsops _options_] [-mntopts _options_] [-vmtype _type_]`

To create a file system that uses a disk group or host volume, use this format: `-fs _file_spec_ [-fstype _type_] [-fsopts _options_] [-mntops _options_] [-hostvol _file_spec_] [-dg _dg_name_] [-vmtype _type_]`

To create a logical or host volume, use this format: `[-hostvol _file_spec_] [-dg _dg_name_] [-fstype _type_] [-vmtype _type_]`

To create a disk group, use this format: `-dg _dg_name_ [-fstype _type_] [-vmtype _type_]`
====
.5+a|
Connect
a|
`snapdrive storage connect -fs _file_spec -nolvm_ -lun _long_lun_name_ [-igroup _ig_name_ [_ig_name ..._]] [-nopersist] [-mntopts options] [-devicetype {shared \| dedicated}][-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage connect -fs _file_spec_ -hostvol _file_spec_ -lun _long_lun_name_ [_lun_name ..._] [-igroup _ig_name_ [_ig_name ..._]][-nopersist] [-mntopts options] [-devicetype {shared \| dedicated}][-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage connect -lun _long_lun_name_ [_lun_name ..._][-igroup _ig_name_ [_ig_name ..._]][-vmtype _type_]`
a|
`snapdrive storage connect -lun _long_lun_name_ [_lun_name..._][-devicetype {shared \| dedicated}][-vmtype _type_]`
a|
`snapdrive storage connect -fs _file_spec_ {-hostvol \| -lvol} _file_spec_ -lun _long_lun_name_ [_lun_name..._] [-devicetype {shared \| dedicated}] [-nopersist] [-mntopts options] [-fstype _type_] [-vmtype _type_]`
.2+a|
Disconnect
a|
`snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._] [-devicetype {shared \| dedicated}][-vmtype _type_]`
a|
`snapdrive storage disconnect {-vg \| -dg \| -fs \| -lvol \| -hostvol} _file_spec_ [_file_spec ..._] [{-vg \| -dg \| -fs \| -lvol \| -hostvol} _file_spec_ ...] ...] [-full] [-devicetype {shared \| dedicated}][-fstype _type_] [-vmtype _type_]`
a|
Resize
a|
`snapdrive storage resize {-dg \| -vg} _file_spec_ [_file_spec ..._]{-growby \| -growto} _size_ [_-addlun_ [-igroup _ig_name_ [_ig_name ..._]]] [{ -reseserve \| -noreserve }]] [-fstype _type_] [-vmtype _type_]`
.8+a|
Show/List
a|
`snapdrive storage { show \| list } -filer _filername_ [_filername ..._] [-verbose] [-quiet] [-capabilities]`
a|
`snapdrive storage { show \| list } -filervol _long_filer_path_ [_filer_path..._][-verbose] [-quiet] [-capabilities]`
a|
`snapdrive storage { show \| list } {-all \| device} [-devicetype {shared \| dedicated}] [-capabilities]`
a|
`snapdrive storage show [-verbose] {-filer _filername_ [_filername..._] \| -filervol _volname_ [_volname..._]} [-devicetype {shared \| dedicated}] [-capabilities]`
a|
`snapdrive storage { show\| list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-quiet] [-status] [-capabilities]`
a|
`snapdrive storage { show \| list } { -vg \| -dg \| -fs \| -lvol \|-hostvol } _file_spec_ [_file_spec ..._] [{ -vg \| -dg \| -fs \| -lvol \| -hostvol } _file_spec_ [_file_spec ..._]] [-verbose] [-quiet [-fstype _type_] [-vmtype _type_] [-status] [-capabilities]`
a|
`snapdrive storage { show \| list } { -filer _filer_name_ [_filer_name ..._] \| -filervol _long_filer_path_ [_filer_path ..._] } [-verbose] [-devicetype {shared \| dedicated}] [-capabilities] [-quiet]`
a|
`snapdrive storage { show \| list } -lun _long_lun_name_ [_lun_name ..._] [-verbose] [-status] [-fstype _type_] [-vmtype _type_] [-capabilities] [-quiet]`

.2+a|
Delete
a|
`snapdrive storage delete [-lun] _long_lun_name_ [_lun_name..._] [-devicetype {shared \| dedicated}] [-fstype _type_] [-vmtype _type_]`
a|
`snapdrive storage delete [-vg \| -dg \| -fs \| -lvol \| -hostvol] _file_spec_ [_file_spec ..._] [{-vg \| -dg \| -fs \| -lvol \| -hostvol} _file_spec_ [_file_spec ..._] ...] [-full] [-devicetype {shared \| dedicated}]] [-fstype _type_] [-vmtype _type_]`
|===
*Related information*

xref:reference_command_line_arguments.adoc[Command-line arguments]
