---
permalink: solaris/reference_stack_requirements.html
sidebar: sidebar
keywords: snap, snapdrive, stack, requirements
summary: SnapDrive for UNIX requires a host operating system, host file systems, NFS, volume managers, FC or iSCSI Host Utilities, storage system licenses, ONTAP software, MultiStore software, and Internet Protocol \(IP\) access. SnapDrive for UNIX also has certain stack requirements which it must fulfill.
---
= Stack requirements
:icons: font
:imagesdir: ../media/

[.lead]
SnapDrive for UNIX requires a host operating system, host file systems, NFS, volume managers, FC or iSCSI Host Utilities, storage system licenses, ONTAP software, MultiStore software, and Internet Protocol (IP) access. SnapDrive for UNIX also has certain stack requirements which it must fulfill.

== Host-side entities

The following is a list of host-side entities:

* The host operating system
* A volume manager
* File system
* Solaris Host Utilities

== Guest-side entities for RDM LUN support

The following is a list of guest-side entities:

* The guest operating system
* A volume manager
* File system
* Solaris iSCSI Host Utility alone is adequate, if the protocol is iSCSI

== SnapDrive for UNIX stack

You must enter acceptable values for the `_multipathing-type_`, `_fstype_`, `_default-transport_`, and `_vmtype_` variables in the `snapdrive.conf` file as provided in the matrix stack. You must verify that the values entered are installed and running in your host system.

[options="header"]
|===
| Host platform| Default transport type| Multipathing type| fstype| vmtype
.4+a|
Solaris x86
a|
FCP
a|
none
a|
ufs
a|
svm
a|
FCP
a|
mpxio
a|
ufs
a|
svm
a|
iSCSI
a|
none
a|
ufs
a|
svm
a|
iSCSI
a|
mpxio
a|
ufs
a|
svm
.5+a|
Solaris SPARC
a|
FCP
a|
DMP
a|
vxfs
a|
vxvm
a|
FCP
a|
none
a|
ufs
a|
svm
a|
FCP
a|
mpxio
a|
ufs
a|
svm
a|
iSCSI
a|
none
a|
ufs
a|
svm
a|
iSCSI
a|
mpxio
a|
ufs
a|
svm
|===

* If you have FCP and iSCSI storage stacks, SnapDrive will only support FCP storage stacks.
+
SnapDrive does not support iSCSI storage stacks for AIX.

* The host operating system and appropriate patches for Solaris are installed.
* The volume manager for Solaris is VxVM and Solaris Volume Manager (SVM).
+
You must install VxVM separately; SVM is included with the Solaris OS.

* Host Utilities are installed in Solaris
* ONTAP software is installed on your storage system.
* MultiStore software is installed on your storage system for a vFiler unit setup.
* Internet Protocol (IP) access is available between the host and storage system.

NetApp modifies host utilities and components on an ongoing basis. You can track this changes by using the Interoperability Matrix, which contains up-to-date information for using NetApp products in a SAN environment.

The storage system license and the MultiStore license constitute the storage system entities.

== Storage system licensing requirements

* An FC, iSCSI, or NFS license, depending on your configuration
* A FlexClone license
* A SnapRestore license on the storage system

*Related information*

xref:concept_unable_to_select_a_storage_stack.adoc[Unable to select a storage stack]

xref:concept_when_to_use_the_snapdrive_configuration_wizard.adoc[SnapDrive configuration wizard]

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]
