---
permalink: solaris/reference_command_line_arguments.html
sidebar: sidebar
keywords: snap, snapdrive, command, line, argument
summary: The SnapDrive for UNIX takes arguments in a specific format.
---
= Command-line arguments
:icons: font
:imagesdir: ../media/

[.lead]
The SnapDrive for UNIX takes arguments in a specific format.

The following table describes the arguments you can specify with the keywords.

Use the format `snapdrive type_name operation_name [<keyword/option> <arguments>]`; for example, if you wanted to create a Snapshot copy called `_snap_hr_` from the host file system `/mnt/dir`, you would enter the following command line:

`*snapdrive snap create -fs/mnt/dir -snapnamesnap_hr*`.

[options="header"]
|===
| Argument| Description
a|
dest_fspec
a|
The name by which the target entity will be accessible after its disk groups or LUNs are connected.
a|
dgname
a|
The name of a disk group or volume group.
a|
d_lun_name
a|
Allows you to specify a destination name that SnapDrive for UNIX uses to make the LUN available in the newly-connected copy of the Snapshot copy.
a|
filername
a|
The name of a storage system.
a|
filer_path
a|
A path name to a storage system object. This name can contain the storage system name and volume, but it does not have to if SnapDrive for UNIX can use default values for the missing components based on values supplied in the previous arguments. The following are examples of path names:

* `test_filer:/vol/vol3/qtree_2`
* `/vol/vol3/qtree_2`
* `qtree_2`

a|
file_spec
a|
The name of a storage entity, such as a host volume, LUN, disk or volume group, file system, or NFS directory tree.

In general, you use the file_spec argument as one of the following:

* An object you want SnapDrive for UNIX to make a Snapshot copy of or to restore from a Snapshot copy
* An object that you want to either create or use when provisioning storage

The objects do not have to be all of the same type. If you supply multiple host volumes, they must all belong to the same volume manager.

If you supply values for this argument that resolve to redundant disk groups or host volumes, the command fails.

Example of incorrect usage: This example assumes dg1 has host volumes hv1 and hv2, with file systems fs1 and fs2. As a result, the following arguments would fail because they involve redundant disk groups or host volumes.

`-dg _dg1_ -hostvol dg1/hv1`

`-dg _dg1_`

`-fs/fs1`

`-hostvol dg1/hv1 -fs /fs1`

Example of correct usage: This example shows the correct usage for this argument.

`-hostvol dg1/hv1 dg1/hv2`

`-fs /fs1 /fs2`

`-hostvol dg1/hv1 -fs /fs2`

a|
fspec_set
a|
Used with the snap connect command to identify:

* A host LVM entity
* A file system contained on a LUN

The argument also lets you specify a set of destination names that SnapDrive for UNIX uses when it makes the entity available in the newly connected copy of the Snapshot copy.

The format for fspec_set is: `{ -vg \| -dg \| -fs \| -lvol \| -hostvol } _src_fspec_ [_dest_fspec_] [{ -destdg \| -destvg } _dg_name_] [{ - destlv \| -desthv } _lv_name_]`

.2+a|
host_lvm_fspec
a|
Lets you specify whether you want to create a file system, logical volume, or disk group when you are executing the storage create command. This argument might have any of the three formats as described in the following. The format you use depends on the entity you want to create.

NOTE: The `-dg` and `-vg` options are synonyms that reflect the fact that some operating systems refer to disk groups and others refer to volume groups. In addition, `-lvol` and `-hostvol` are also synonyms. This guide uses `-dg` to refer to both disk groups and volume groups and `-hostvol` to refer to both logical volumes and host volumes.

a|
To create a file system, use this format: `-fs file_spec [-fstype _type_] [-fsopts _options_] [-hostvol _file_spec_] [-dg _dg_name_]` To create a logical or host volume, use this format: `[-hostvol _file_spec_] [-dg _dg_name_] \| -hostvol` To create a disk or volume group, use this format: `file_spec [-dg _dg_name_] \| -dg _dg_name_`

You must name the top-level entity that you are creating. You do not need to supply names for any underlying entities. If you do not supply names for the underlying entities, SnapDrive for UNIX creates them with internally generated names.

If you specify that SnapDrive for UNIX create a file system, you must specify a type that SnapDrive for UNIX supports with the host LVM. These types include `vxfs` or `ufs`.

The option `-fsopts` is used to specify options to be passed to the host operation that creates the new file system; for example, `mkfs`.

a|
ig_name
a|
The name of an initiator group.
a|
long_filer_path
a|
A path name that includes the storage system name, volume name, and possibly other directory and file elements within that volume. The following are examples of long path names:

`test_filer:/vol/vol3/qtree_2`

`10.10.10.1:/vol/vol4/lun_21`

a|
long_lun_name
a|
A name that includes the storage system name, volume, and LUN name. The following is an example of a long LUN name:

`test_filer:/vol/vol1/lunA`

a|
long_snap_name
a|
A name that includes the storage system name, volume, and Snapshot copy name. The following is an example of a long Snapshot copy name: `test_filer:/vol/account_vol:snap_20040202`

With the `snapdrive snap show` and `snapdrive snap delete` commands, you can use the asterisk (*) character as a wildcard to match any part of a Snapshot copy name. If you use a wildcard character, you must place it at the end of the Snapshot copy name. SnapDrive for UNIX displays an error message if you use a wildcard at any other point in a name.

Example: This example uses wildcards with both the snap show command and the snap delete command: snap show myfiler:/vol/vol2:mysnap*

`myfiler:/vol/vol2:/yoursnap* snap show myfiler:/vol/vol1/qtree1:qtree_snap* snap delete 10.10.10.10:/vol/vol2:mysnap* 10.10.10.11:/vol/vol3:yoursnap* hersnap`

Limitation for wildcards: You cannot enter a wildcard in the middle of a Snapshot copy name. For example, the following command line produces an error message because the wildcard is in the middle of the Snapshot copy name: banana:``/vol/vol1:my*snap`

a|
lun_name
a|
The name of a LUN. This name does not include the storage system and volume where the LUN is located. The following is an example of a LUN name: `_lunA_`
a|
path
a|
Any path name.
a|
prefix_string
a|
prefix used in the volume clone's name generation
a|
s_lun_name
a|
Indicates a LUN entity that is captured in the Snapshot copy specified by `_long_snap_name_`.
|===
*Related information*

xref:reference_storage_provisioning_command_lines.adoc[Storage provisioning command lines]
