---
permalink: solaris/reference_some_configuration_commands.html
sidebar: sidebar
keywords: 
summary: 'There are few commands that help you in configuring SnapDrive for UNIX.'
---
= Some configuration commands
:icons: font
:imagesdir: ../media/

[.lead]
There are few commands that help you in configuring SnapDrive for UNIX.

The following table summarizes additional commands that are helpful in configuring SnapDrive for UNIX:

|===
| Command or action| Description
a|
Configuring and verifying your version of SnapDrive for UNIX software
a|
snapdrive config show
a|
Check the values in the snapdrive.conf file.
a|
snapdrive version
a|
Check the version of SnapDrive for UNIX.
a|
snapdrived start
a|
Start the SnapDrive for UNIX daemon.
a|
snapdrive config prepare luns -count count_value[-devicetype {shared | dedicated}]
a|
Prepare the host for creating a specific number of LUNs as well as to determine how many LUNs you can create.
a|
snapdrive config set -viadmin <user> <viadmin_name>
a|
Prepare the guest for creating RDM LUN on Solaris x86 guest OS.

NOTE: You only use these commands on Solaris x86 host by using FCP protocol with no host utilities.

a|
snapdrive clone split
a|
Estimate, start, stop, and query the status of split for a volume clone or a LUN clone.

a|
snapdrive config check cluster
a|
Check for the following in the SFRAC cluster environment on a Solaris host:

* SnapDrive for UNIX version
* Group Membership Services/Atomic Broadcast (GAB) configuration
* Cluster status
* Host Cluster Volume Manager (CVM) status
* Usage of rsh or ssh for a secure communication within the host cluster nodes
* Differences in setting the following configuration variable values in the snapdrive.conf file:
 ** default-transport= FCP
 ** multipathing-type=DMP

a|
Edit the variables in the snapdrive.conf file.
a|
Change the path name and options for the log files. SnapDrive for UNIX logs information to three files:

* An audit file
* A recovery file
* A trace file

a|
Setting and displaying access control permissions between a host and a storage system.
a|
Edit the access control permissions file (sd hostname.prbac) on the storage system associated with that host.
a|
Specify the access control permissions a host has on a storage system. You can set the following access levels for a host on a storage system:

* NONE--No access.
* SNAP CREATE--Create Snapshot copies.
* SNAP USE--Delete and rename Snapshot copies.
* SNAP ALL--Create, restore, delete, and rename Snapshot copies.
* STORAGE CREATE DELETE--Create, resize, and delete storage.
* STORAGE USE--Connect and disconnect storage.
* STORAGE ALL--Create, delete, connect, and disconnect storage.
* ALL ACCESS--All operations.

a|
snapdrive config access show <filer_name>
a|
Display information about the access control permissions a host has to a storage system.
a|
snapdrive config delete <filername> [<filername> . . .]
a|
Remove the specified user name-password pair from SnapDrive for UNIX.
|===
