---
permalink: solaris/task_connecting_to_asnapshot_copy_thatcontains_luns.html
sidebar: sidebar
keywords: snap, snapdrive, connect, snapshot, copy, lun
summary: You can connect to a Snapshot copy that contains LUNs by using the snapdrive snap connect command.
---
= Connecting to a Snapshot copy that contains LUNs
:icons: font
:imagesdir: ../media/

[.lead]
You can connect to a Snapshot copy that contains LUNs by using the `snapdrive snap connect` command.

.Steps

. Enter the following command syntax to connect to a Snapshot copy that contains LUNs:
+
`*snapdrive snap connect -lun _s_lun_name d_lun_name_ [[-lun] _s_lun_name d_lun_name..._ -snapname _long_snap_name_ [-igroup _ig_name_ [_ig_name..._]] [-split]*`
+
NOTE: The `_s_lun_name_` and `_d_lun_name_` should be in the format lun_name or qtree_name/lun_name.

SnapDrive for UNIX clones the LUNs you specify and connects them to a new location.

The following example connects the LUN mylun1, in hornet/vol/vol1/tuesdaysnapshot to mylun1copy:

----
# ./snapdrive snap connect -lun mylun1 mylun1copy -snapname
hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1) mapping new lun(s) ... done
discovering new lun(s) ... done
----

The following example connects two LUNs, mylun1 and mylun2, to mylun1copy and mylun2copy, respectively:

----
# ./snapdrive snap connect -lun mylun1 mylun1copy -lun mylun2
mylun2copy -snapname hornet:/vol/vol1:tuesdaysnapshot
connecting hornet:/vol/vol1/mylun1:
LUN copy mylun1copy ... created
(original: hornet:/vol/vol1/mylun1)
mapping new lun(s) ... done
connecting hornet:/vol/vol1/mylun2:
LUN copy mylun2copy ... created
(original: hornet:/vol/vol1/mylun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
----

The following example connects the LUN lun1_0 to snapshot lech:/vol/vol1:rrt:

----

snapdrive snap connect -fs /mnt/fs /mnt/fs1  -snapname lech:/vol/vol1:rrt
connecting /mnt/fs:
   LUN copy lun1_0 ... created
     (original: lech:/vol/vol1/lun1)
   exporting new lun(s) to Guest OS ... done
   discovering new lun(s) ... done
Successfully connected to snapshot lech:/vol/vol1:rrt
        file system: /mnt/fs1
----
