---
permalink: solaris/task_setting_values_in_the_snapdrive_conf_file.html
sidebar: sidebar
keywords: snap, snapdrive, value, file
summary: You can change the values in the snapdrive.conf file or add new name-value pairs.
---
= Setting values in the snapdrive.conf file
:icons: font
:imagesdir: ../media/

[.lead]
You can change the values in the `snapdrive.conf` file or add new name-value pairs.

You must be logged in as a root user.

.Steps

. Back up the `snapdrive.conf` file.
. Open the `snapdrive.conf` file in a text editor.
. To add a name-value pair, use the following format:
+
`*config-option-name=value _value_ # optional comment*`
+
`_config-option-name_` is the name of the variable you want to configure; for example, audit-log-file. `_value_` is the value you want to assign to this option.
+
If you want to include a comment with the name-value pair, precede the comment with a number sign (#).
+
You should enter only one name-value pair, per line.
+
If the name or the value uses a string, enclose the string in either single ('`) or double (") quotation marks. You can place the quotation marks either around the entire name-value pair or around only the value. The following examples show how you can use quotation marks and comments with name-value pairs:
+
`*"config-option-one=string with white space" # double quotes around the pair*`
+
`*config-option-two="string with white space" # double quotes around the value*`
+
`*config-option-2B=`'string with white space`' # single quotes around the value*`

. To modify a name-value pair, replace the current value with the new value.
+
Follow the steps below to ensure that the default values are recorded in the file.

 .. Add the sign (#) to the line that you want to modify.
 .. Copy the line.
 .. Activate the copied text by removing the number sign (#).
 .. Modify the value.

+
If you want to specify a blank value (for example, to disable the audit log file), enter a pair of double quotation marks ("").

. Save the file after you make your changes.
+
SnapDrive for UNIX automatically checks this file each time it starts. Your changes take effect the next time it starts.

. Restart the SnapDrive for UNIX daemon by using the `snapdrived restart` command.
+
Restarting the daemon is necessary for `snapdrive.conf` file changes to take effect.
