---
permalink: linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html
sidebar: sidebar
keywords: snapdrive, snap, connect, hosts, storage, system
summary: For successful SnapDrive for UNIX operations, you must set up your storage virtual machines \(SVMs, formerly known as Vservers\)
---
= Connecting Linux hosts to storage systems
:icons: font
:imagesdir: ../media/

[.lead]
For successful SnapDrive for UNIX operations, you must set up your storage virtual machines (SVMs, formerly known as Vservers).

* You must have assigned the aggregates that contain volumes to the SVMs aggregate list to execute the SnapDrive for UNIX operations.
* You must have one or more SVMs created to serve data from the cluster.
+
The IP address of the SVM management logical interface (LIF) must be mapped with the SVM name, either in the Domain Name Service (DNS) or in the `/etc/hosts` file.

* If you are running ONTAP 8.2.2 or earlier, you must first create a user on the cluster management server, also called adminSVM, by running the `*snapdrive config set -cserver _csadmin_name cserver_name_*` command.

.Steps

. Create a user on the data SVM:
+
`*snapdrive config set vsadmin_name _Vserver_name_*`
+
NOTE: The `_Vserver_name_` is the name of the SVM and must be mapped to the management LIF IP address for the SVM.

. Verify that the SVM is configured in SnapDrive for UNIX:
+
`*snapdrive config list*`
+
The command lists the user name and IP address of the cluster management server and data SVM.

. Modify the management interface path to the data interface path of the SVM:
+
`*snapdrive config set -mgmtpath _management_interface_path data_interface_path_*`
. Verify that all data and management interfaces are configured properly:
+
`*snapdrive config list -mgmtpath*`

// 2022 DEC 9, snapdrive-unix-issues-10