---
permalink: linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html
sidebar: sidebar
keywords: SnapDrive for UNIX
summary: 'For successful SnapDrive for UNIX operations, you must set up your storage virtual machines \(SVMs, formerly known as Vservers\)'
---
= Connecting Linux hosts to storage systems
:icons: font
:imagesdir: ../media/

[.lead]
For successful SnapDrive for UNIX operations, you must set up your storage virtual machines (SVMs, formerly known as Vservers)

* You must have assigned the aggregates that contain volumes to the SVMs aggregate list to execute the SnapDrive for UNIX operations.
* You must have one or more SVMs created to serve data from the cluster.
+
The IP address of the SVM management logical interface (LIF) must be mapped with the SVM name, either in the Domain Name Service (DNS) or in the /etc/hosts file.

. If you are running ONTAP 8.2.2 or earlier, create a user on the cluster management server, also called adminSVM: snapdrive config set -cserver csadmin_namecserver_name
+
If you are running ONTAP 8.2.3 or later, then skip this step.

. Create a user on the data SVM: snapdrive config setvsadmin_nameVserver_name
. Verify that the SVM is configured in SnapDrive for UNIX: snapdrive config list
+
The command lists the user name and IP address of the cluster management server and data SVM.

. Modify the management interface path to the data interface path of the SVM: snapdrive config set -mgmtpath management_interface_pathdata_interface_path
. Verify that all data and management interfaces are configured properly: snapdrive config list -mgmtpath
